# Generated by Django 4.2.7 on 2024-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=20)),
                ("yearOfEstablishment", models.PositiveIntegerField()),
                ("email", models.EmailField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
