# Generated by Django 4.2.7 on 2023-11-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmployeeRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fName", models.CharField(max_length=255)),
                ("lName", models.CharField(max_length=255)),
                ("Department", models.CharField(max_length=255)),
                ("Supervisor", models.CharField(max_length=255)),
            ],
        ),
    ]
