# Generated by Django 4.2.7 on 2023-11-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeroster",
            name="emailAddress",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
