# Generated by Django 4.2.7 on 2023-12-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0003_students"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("EMPLOYEE_ID", models.IntegerField(null=True)),
                ("FIRST_NAME", models.CharField(max_length=255)),
                ("LAST_NAME", models.CharField(max_length=255)),
                ("JOB_ID", models.CharField(max_length=255)),
                ("SALARY", models.IntegerField(null=True)),
            ],
        ),
    ]
